import { useRef } from 'react';
import { useGLTF, useTexture } from '@react-three/drei';
import { EffectComposer, SelectiveBloom } from '@react-three/postprocessing';
import { BlendFunction } from 'postprocessing';
import * as THREE from 'three';

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 optimized-room.glb 
*/

const RoomModelOne = (props) => {
	const { nodes, materials } = useGLTF('/models/optimized-room.glb');
	const screensRef = useRef();
	const matcapTexture = useTexture('/images/textures/mat1.png');

	const curtainMaterial = new THREE.MeshPhongMaterial({
		color: '#3C394D',
	});

	const bodyMaterial = new THREE.MeshPhongMaterial({
		map: matcapTexture,
	});

	const compMaterial = new THREE.MeshStandardMaterial({
		color: '#fff',
	});

	return (
		<group {...props} dispose={null}>
			<EffectComposer>
				<SelectiveBloom
					selection={screensRef}
					intensity={0.5}
					luminanceThreshold={0.22}
					luminanceSmoothing={0.9}
					blendFunction={BlendFunction.ADD}
				/>
			</EffectComposer>
			<mesh
				geometry={nodes._________6_blinn1_0.geometry}
				material={curtainMaterial}
			/>
			<mesh geometry={nodes.body1_blinn1_0.geometry} material={bodyMaterial} />
			<mesh geometry={nodes.comp_blinn1_0.geometry} material={compMaterial} />
			<mesh
				ref={screensRef}
				geometry={nodes.emis_lambert1_0.geometry}
				material={materials.lambert1}
			/>
			<mesh
				geometry={nodes._________6_blinn1_0.geometry}
				material={nodes._________6_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.body1_blinn1_0.geometry}
				material={nodes.body1_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.cabin_blinn1_0.geometry}
				material={nodes.cabin_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.chair_body_blinn1_0.geometry}
				material={nodes.chair_body_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.comp_blinn1_0.geometry}
				material={nodes.comp_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.emis_lambert1_0.geometry}
				material={nodes.emis_lambert1_0.material}
			/>
			<mesh
				geometry={nodes.handls_blinn1_0.geometry}
				material={nodes.handls_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.keyboard_blinn1_0.geometry}
				material={nodes.keyboard_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.kovrik_blinn1_0.geometry}
				material={nodes.kovrik_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.lamp_bl_blinn1_0.geometry}
				material={nodes.lamp_bl_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.lamp_white_blinn1_0.geometry}
				material={nodes.lamp_white_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.miuse_blinn1_0.geometry}
				material={nodes.miuse_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.monitor2_blinn1_0.geometry}
				material={nodes.monitor2_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.monitor3_blinn1_0.geometry}
				material={nodes.monitor3_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.pCylinder5_blinn1_0.geometry}
				material={nodes.pCylinder5_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.pillows_blinn1_0.geometry}
				material={nodes.pillows_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.polySurface53_blinn1_0.geometry}
				material={nodes.polySurface53_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.radiator_blinn1_0.geometry}
				material={nodes.radiator_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.radiator_blinn1_0001.geometry}
				material={nodes.radiator_blinn1_0001.material}
			/>
			<mesh
				geometry={nodes.railing_blinn1_0.geometry}
				material={nodes.railing_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.red_bttns_blinn1_0.geometry}
				material={nodes.red_bttns_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.red_vac_blinn1_0.geometry}
				material={nodes.red_vac_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.stylus_blinn1_0.geometry}
				material={nodes.stylus_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.table_blinn1_0.geometry}
				material={nodes.table_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.tablet_blinn1_0.geometry}
				material={nodes.tablet_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.triangle_blinn1_0.geometry}
				material={nodes.triangle_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.vac_black_blinn1_0.geometry}
				material={nodes.vac_black_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.vacuum1_blinn1_0.geometry}
				material={nodes.vacuum1_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.vacuumgrey_blinn1_0.geometry}
				material={nodes.vacuumgrey_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.vires_blinn1_0.geometry}
				material={nodes.vires_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.window_blinn1_0.geometry}
				material={nodes.window_blinn1_0.material}
			/>
			<mesh
				geometry={nodes.window4_phong1_0.geometry}
				material={nodes.window4_phong1_0.material}
			/>
		</group>
	);
};

useGLTF.preload('/models/optimized-room.glb');

export default RoomModelOne;
